### ISSUE TITLE
Household Aggregations

### ISSUE THREAD

**Issue by gwenbeebe** [COHHIO/COHHIO_HMIS#109]
I'm looking at the active from the user's perspective, and I have a couple systemic questions about what is intended to be rolled up and what isn't. If we decide to roll up either of these, the sections may also need to be moved up higher in the code, depending on the disposition of Issue #106 

For instance, we have a column that's labelled Income, but it's only looking at the income of the head of household. As a user, I would probably expect that to include whether anyone in the household has income, not just the person shown, but that could be a reflection of the set-up I'm used to?

Another example is score: it's rare, but we have a few instances of someone who is not listed as head of household having a higher score than the head of household. It may make sense to display the highest score in the last year for all household members instead of just the head of household's. To see those households, run the following code after the scores are joined to the `active_list` data frame:
```
active_list_test <- active_list %>%
  group_by(HouseholdID) %>%
  mutate(highest_score = max(Score)) %>%
  ungroup() %>%
  filter(Score != highest_score & hoh == 1)
```

**Comment by kiadso** [comment]
I agree completely about Income being Household-level. I purposely do not show the amount on the report so that those with higher incomes don't get priveleged over those with lower incomes. We only show the yes/no because one of our Performance Measures is that at least 40% of PH projects households have no income. (Or some percentage.)
I'm hesitant about the Scores because we tell the users only Scores on HoHs count, and like opening that up to return the highest score in the hh is maybe overcompensating, but BUT BUT like that is what we're trying to do here with this Prioritization report. We are guessing HoH, counties, chronic (now), so like why not scores. Anyway, I think I agree with your proposed change though, taking the highest score in the hh for the Active List only! Thank you so much for alerting about this!
