### ISSUE TITLE
Participant Definition?

### ISSUE THREAD

**Issue by gwenbeebe** [COHHIO/COHHIO_HMIS#145]
This scoring report is a beast! Especially with all the neat functions and modular pieces that have been added in the last few months. I'm starting to feel like I'm getting my bearings, and my first definition question is on the non-cash benefits points. 

The 06 script is calculating it with `pe_adults_moved_in_leavers`, and that dataframe is limited to folks leaving during that time period that had a move-in date for housing programs. Why aren't we including folks that exited housing programs without a housing move-in date? I'm guessing it's part of the participant definition, but I'm not seeing that spelled out in the scoring documentation that I have so wanted to double-check.

**Comment by kiadso** [comment]
Thanks for asking- I'm checking with EM, we'll make Appendix B clearer and be sure what I'm doing is what they think I'm doing! :)

**Comment by kiadso** [comment]
Appendix is much clearer now as to who is being counted. The cohorts are decided by the committee, but many agencies enter everyone who's eligible, then try to get them all housing knowing they won't house everyone. I don't know what the expectation is for those who are eligible but aren't housed, so that's probably why we're not counting them. Thanks for pressing for clarity here, I found a couple of things that were mistakes in the Appendix that way. :)
